name: Generate Zotero to CSL Mappings HTML

on:
  workflow_dispatch:  # Manual trigger

jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests jq

      - name: Fetch the latest schema version
        id: fetch_version
        run: |
          # Fetch the schema JSON from GitHub
          curl -s https://raw.githubusercontent.com/zotero/zotero-schema/master/schema.json > schema.json
          
          # Extract the version from the schema
          SCHEMA_VERSION=$(jq -r '.version' schema.json)
          
          # Output the version
          echo "Schema version is $SCHEMA_VERSION"
          
          # Check if the version has changed by comparing with the stored version
          if [ -f last_known_version.txt ]; then
            LAST_KNOWN_VERSION=$(cat last_known_version.txt)
            echo "Last known version is $LAST_KNOWN_VERSION"
          else
            LAST_KNOWN_VERSION="none"
            echo "No previous version found."
          fi

          # Compare versions, proceed only if different
          if [ "$SCHEMA_VERSION" != "$LAST_KNOWN_VERSION" ]; then
            echo "New version found, proceed with generating the HTML."
            echo $SCHEMA_VERSION > last_known_version.txt
            echo "::set-output name=version_changed::true"
          else
            echo "No new version. Skip the process."
            echo "::set-output name=version_changed::false"
          fi

      - name: Generate HTML if version changed
        if: steps.fetch_version.outputs.version_changed == 'true'
        run: |
          python generate_zot2csl.py  # Run your Python script to generate the HTML

      - name: Upload HTML output
        if: steps.fetch_version.outputs.version_changed == 'true'
        uses: actions/upload-artifact@v3  # Updated to use v3
        with:
          name: zotero-schema-html
          path: zotero_schema_output.html

      - name: Notify if no new version
        if: steps.fetch_version.outputs.version_changed == 'false'
        run: |
          echo "No new version detected, skipping HTML generation."
