name: Generate Zotero to CSL Mappings HTML

on:
  workflow_dispatch:  # Manual trigger

jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate HTML output
        run: |
          python generate_zot2csl.py

      - name: Commit and push HTML output to repository
        run: |
          # Ensure the docs directory exists
          mkdir -p docs
          # Move the generated file (index.html) to the docs directory
          mv index.html docs/index.html
          
          # Configure Git
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          # Stage, commit, and push changes
          git add docs/index.html
          git commit -m "Update Zotero to CSL HTML mapping - forced update"
          git push
